### ISSUE TITLE
[ziwooda] configure cluster on OCI instance and save snapshot

### ISSUE THREAD

**Issue by ziwooda** [JUJY-OIDC/etcd-autobackup#21]
**TASK LISTS**
- [x] VM에 클러스터 환경 구축 (kubeadm)
- [x] etcd cert 생성
- [x] etcdctl snapshot 생성 test

**Comment by ziwooda** [comment]
✨TASK1 : Configuring Cluster
1. CRI endpoint ISSUE
- cri-dockerd 설치
- `--cri-socket` 옵션으로 `cri-dockerd.sock` 지정

<br />

2. CNI로 Calico 배포 & `kubeadm join`으로 control plane 노드 실행 성공
```
kubectl get nodes
NAME                 STATUS   ROLES           AGE   VERSION
oidc-instance-jujy   Ready    control-plane   50m   v1.27.3
```

**Comment by ziwooda** [comment]
✨TASK2 : ETCD 인증서 받기
; cfssl 도구 사용

1. etcd 및 etcdctl 설치
2. cfssl 설치
3. client & server API용 CA, pem(공개&비밀) key 생성

**Comment by na3150** [comment]
✨TASK3 : ETCD 인증서 받기
1. etcd 및 etcdctl 설치
2. easyrsa 설치
3. client & server API용 crt, key 생성
